### PR TITLE
Fix transparent find bar

### LINKED ISSUE #258: [UI Bug] Find menu is transparent when opening more than one file in a session
The find menu (⌘+F) has the correct background color for the first file I open in a session, but every subsequent file I open has a transparent find menu.

I was able to replicate this issue every time I restarted Xi. I'm running the current version.

This might be relevant: https://github.com/google/xi-mac/issues/194#issuecomment-408353412

Thanks!

### PR DESCRIPTION
**Pull request by ryanbloom**
Fixes #258

### CODE REVIEW

File: XiEditor/Search.swift [hunk 1]
```diff
@@ -15,6 +15,11 @@
 import Cocoa
 import Swift
 
+extension NSColor {
```
Comment (cmyr) [inline XiEditor/Search.swift]: as an item of personal style I might've just had a `static var fallbackBackgroundGray` on the `FindViewController` class instead of doing this as an extension, but I don't have an argument beyond personal taste, so I think this is fine. :)
